### PR TITLE
Mail List action bar improvements

### PR DESCRIPTION
**Pull request by Tiktack**
1. Action bar now can be shown/hidden from settings
2. Custom pivot changed to community toolkit one to match the styles 
3. Action bar has dynamic list of actions ( the same like context menu)
4. Fixed incorrect logic for dynamic setFlag/clearFlag

Example: 

1. Action bar enabled 
image
2. Action bar disabled 
image

### CODE REVIEW

**Review by bkaankose — APPROVED** [review]

**Comment by edge261** [comment]
Hi @Tiktack 

A small thing I noticed is that the indicator below the pivot is not properly centered with the text. Maybe it's a text alignment issue...

**Comment by bkaankose** [comment]
image

By default it's not centered in the control itself.

**Comment by Tiktack** [comment]
@bkaankose, 
It's not really true :) 
Looks like hidden text adds some padding ( idk why )
Example: 
With hidden text: 
image
Without hidden text 
image

**Comment by edge261** [comment]
Would be possible to make appear the action bar automatically when you select one or more emails?

Also, I think it would be good to have tooltips in the action bar with the name of the button.

**Comment by Tiktack** [comment]
Yeah, tooltips is a miss. For toolbar you can all the time use context menu. Usually it's one time operation, tradeoff is 2 clicks instead of 1 for real estate :D

**Comment by Tiktack** [comment]
Found the real reason for not centered text. StackPanel "spacing" property applied even for hidden elements... As I said, will fix it later.
image

**Comment by edge261** [comment]
Not sure if I can mention it here, but when I select an email using the button that enables the checkboxes, it opens the first email I select. 

I think it should not open it... just select it. (not sure of what the behavior is on the OG mail app)

**Comment by bkaankose** [comment]
> Not sure if I can mention it here, but when I select an email using the button that enables the checkboxes, it opens the first email I select.
> 
> I think it should not open it... just select it. (not sure of what the behavior is on the OG mail app)

It's working as expected. Windows Mail and even current Outlook works the same.

**Pull request merged**
